services:
  discovery-server:
    build:
      context: ./spring-petclinic-discovery-server
      dockerfile: ../docker/Dockerfile
      args:
        ARTIFACT_NAME: target/spring-petclinic-discovery-server-3.2.4
    environment:
      - JAVA_TOOL_OPTIONS=
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
      - SPRING_PROFILES_ACTIVE=docker
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tracing-server:9411/api/v2/spans

  customers-service:
    build:
      context: ./spring-petclinic-customers-service
      dockerfile: ../docker/Dockerfile
      args:
        ARTIFACT_NAME: target/spring-petclinic-customers-service-3.2.4
    environment:
      - JAVA_TOOL_OPTIONS=
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
      - SPRING_PROFILES_ACTIVE=docker,postgres
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tracing-server:9411/api/v2/spans
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5433/postgres?sslmode=require
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Samsaran@2026
      - SPRING_SQL_INIT_SCHEMA_LOCATIONS=classpath*:db/postgres/schema.sql
      - SPRING_SQL_INIT_DATA_LOCATIONS=classpath*:db/postgres/data.sql
      - SPRING_SQL_INIT_MODE=always

  visits-service:
    build:
      context: ./spring-petclinic-visits-service
      dockerfile: ../docker/Dockerfile
      args:
        ARTIFACT_NAME: target/spring-petclinic-visits-service-3.2.4
    environment:
      - JAVA_TOOL_OPTIONS=
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
      - SPRING_PROFILES_ACTIVE=docker,postgres
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tracing-server:9411/api/v2/spans
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5433/postgres?sslmode=require
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Samsaran@2026
      - SPRING_SQL_INIT_SCHEMA_LOCATIONS=classpath*:db/postgres/schema.sql
      - SPRING_SQL_INIT_DATA_LOCATIONS=classpath*:db/postgres/data.sql
      - SPRING_SQL_INIT_MODE=always

  vets-service:
    build:
      context: ./spring-petclinic-vets-service
      dockerfile: ../docker/Dockerfile
      args:
        ARTIFACT_NAME: target/spring-petclinic-vets-service-3.2.4
    environment:
      - JAVA_TOOL_OPTIONS=
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
      - SPRING_PROFILES_ACTIVE=docker,postgres
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tracing-server:9411/api/v2/spans
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5433/postgres?sslmode=require
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Samsaran@2026
      - SPRING_SQL_INIT_SCHEMA_LOCATIONS=classpath*:db/postgres/schema.sql
      - SPRING_SQL_INIT_DATA_LOCATIONS=classpath*:db/postgres/data.sql
      - SPRING_SQL_INIT_MODE=always

  api-gateway:
    build:
      context: ./spring-petclinic-api-gateway
      dockerfile: ../docker/Dockerfile
      args:
        ARTIFACT_NAME: target/spring-petclinic-api-gateway-3.2.4
    environment:
      - JAVA_TOOL_OPTIONS=
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
      - SPRING_PROFILES_ACTIVE=docker
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tracing-server:9411/api/v2/spans

  admin-server:
    build:
      context: ./spring-petclinic-admin-server
      dockerfile: ../docker/Dockerfile
      args:
        ARTIFACT_NAME: target/spring-petclinic-admin-server-3.2.4
    environment:
      - JAVA_TOOL_OPTIONS=
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
      - SPRING_PROFILES_ACTIVE=docker
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tracing-server:9411/api/v2/spans

  grafana-server:
    environment:
      - GF_DATABASE_PASSWORD=Samsaran@2026