spring:
  application:
    name: vets-service
  cache:
    cache-names: vets
  profiles:
    active: production
  zipkin:
    base-url: http://tracing-server:9411
  sleuth:
    sampler:
      probability: 1.0
    
eureka:
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

