spring:
  application:
    name: discovery-server
  zipkin:
    base-url: http://tracing-server:9411
  sleuth:
    sampler:
      probability: 1.0

# Avoid some debugging logs at startup
logging:
  level:
    org:
      springframework:
        boot: INFO
        web: INFO

eureka:
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true


