server.port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-petclinic/spring-petclinic-microservices-config
          default-label: main
        #        native:
        #          searchLocations: classpath:/config
        # Use the File System Backend to avoid git pulling. Enable "native" profile in the Config Server.
  zipkin:
    base-url: http://tracing-server:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
