trigger: none

parameters:
  - name: currentDirectory
    type: string
    default: '$(Build.SourcesDirectory)'

steps:
- task: Maven@4
  displayName: Build spring-petclinic-microservices using Maven
  inputs:
      mavenPOMFile: '${{parameters.currentDirectory}}/spring-petclinic-microservices/pom.xml' # string. Required. Maven POM file. Default: pom.xml.
      goals: 'clean install -P buildDocker' # string. Goal(s). Default: package.
      options: '-DskipTests' # string. Options. 
      javaHomeOption: 'JDKVersion' # 'JDKVersion' | 'Path'. Alias: javaHomeSelection. Required. Set JAVA_HOME by. Default: JDKVersion.
      jdkVersionOption: '1.25' # Alias: jdkVersion. Optional. Use when javaHomeSelection = JDKVersion.
      mavenVersionOption: 'Default' # 'Default' | 'Path'. Alias: mavenVersionSelection. Required. Maven version. Default: Default.
    